Feature EPL-1296: Add how to create junit testcases page
etendosoftware/docs pull request #134
Opened 2024-03-12 18:34 UTC by facumoyanosmf

2024-03-15 13:50 UTC, isaiasb-etendo commented on docs/developer-guide/etendo-classic/how-to-guides/how-to-create-jest-testcases.md
> +Jest  is a testing framework created by Facebook and currently used as the
In OB wiki there are omitted links here
https://wiki.openbravo.com/wiki/How_to_create_Jest_testcases

2024-03-15 14:58 UTC, RomanMagnoli approved these changes

2024-03-15 19:17 UTC, Gremiger approved these changes

2024-03-18 13:03 UTC, valeg-etendo requested changes

2024-03-18 17:55 UTC, valeg-etendo approved these changes

2024-03-18 18:10 UTC, merged