EPL-1302: [How-to] How to add a canvas field to a Form or Grid
etendosoftware/docs pull request #138
Opened 2024-03-15 14:17 UTC by RomanMagnoli

2024-03-18 11:28 UTC, valenvivaldi requested changes
Quitar referencia a OB

2024-03-18 13:57 UTC, valeg-etendo requested changes

2024-03-18 13:57 UTC, valeg-etendo commented on docs/developer-guide/etendo-classic/how-to-guides/How_to_add_a_canvas_field_to_a_Form_or_Grid.md
> +![](/assets/developer-guide/etendo-classic/how-to-guides/How_to_add_a_canvas_field_to_a_Form_or_Grid-1.png)
```suggestion
![](../../../assets/developer-guide/etendo-classic/how-to-guides/How_to_add_a_canvas_field_to_a_Form_or_Grid-1.png)
```

2024-03-18 13:57 UTC, valeg-etendo commented on docs/developer-guide/etendo-classic/how-to-guides/How_to_add_a_canvas_field_to_a_Form_or_Grid.md
> +It is also possible to add in-line properties in the "Clientclass" field, for example, 'OBEXAPP_SalesOrderActionButton {"title":
```suggestion
It is also possible to add in-line properties in the `"Clientclass"` field, for example, 'OBEXAPP_SalesOrderActionButton {"title":
```

2024-03-18 13:57 UTC, valeg-etendo commented on docs/developer-guide/etendo-classic/how-to-guides/How_to_add_a_canvas_field_to_a_Form_or_Grid.md
> +![](/assets/developer-guide/etendo-classic/how-to-guides/How_to_add_a_canvas_field_to_a_Form_or_Grid-2.png)
```suggestion
![](../../../assets/developer-guide/etendo-classic/how-to-guides/How_to_add_a_canvas_field_to_a_Form_or_Grid-2.png)
```

2024-03-18 13:57 UTC, valeg-etendo commented on docs/developer-guide/etendo-classic/how-to-guides/How_to_add_a_canvas_field_to_a_Form_or_Grid.md
> +![](/assets/developer-guide/etendo-classic/how-to-guides/How_to_add_a_canvas_field_to_a_Form_or_Grid-3.png)
```suggestion
![](../../../assets/developer-guide/etendo-classic/how-to-guides/How_to_add_a_canvas_field_to_a_Form_or_Grid-3.png)
```

2024-03-18 13:57 UTC, valeg-etendo commented on docs/developer-guide/etendo-classic/how-to-guides/How_to_add_a_canvas_field_to_a_Form_or_Grid.md
> +    * grid: the grid object
```suggestion
    * `grid`: the grid object 
```

2024-03-18 13:57 UTC, valeg-etendo commented on docs/developer-guide/etendo-classic/how-to-guides/How_to_add_a_canvas_field_to_a_Form_or_Grid.md
> +    * rowNum: the row number/record index for which the canvas is used
```suggestion
    * `rowNum`: the row number/record index for which the canvas is used 
```

2024-03-18 13:57 UTC, valeg-etendo commented on docs/developer-guide/etendo-classic/how-to-guides/How_to_add_a_canvas_field_to_a_Form_or_Grid.md
> +    * record: the record for which the canvas is used
```suggestion
    * `record`: the record for which the canvas is used 
```

2024-03-18 13:57 UTC, valeg-etendo commented on docs/developer-guide/etendo-classic/how-to-guides/How_to_add_a_canvas_field_to_a_Form_or_Grid.md
> +    * colNum: the column in which the canvas is shown
```suggestion
    * `colNum`: the column in which the canvas is shown 
```

2024-03-18 13:57 UTC, valeg-etendo commented on docs/developer-guide/etendo-classic/how-to-guides/How_to_add_a_canvas_field_to_a_Form_or_Grid.md
> +    * field: the field where the canvas is used
```suggestion
    * `field`: the field where the canvas is used 
```

2024-03-18 13:57 UTC, valeg-etendo commented on docs/developer-guide/etendo-classic/how-to-guides/How_to_add_a_canvas_field_to_a_Form_or_Grid.md
> +  * If the canvas has a property noTitle with the value true then in form mode no title/label is displayed
```suggestion
  * If the canvas has a property noTitle with the value `true` then in form mode no title/label is displayed 
```

2024-03-18 14:12 UTC, RomanMagnoli commented on docs/developer-guide/etendo-classic/how-to-guides/How_to_add_a_canvas_field_to_a_Form_or_Grid.md
> +It is also possible to add in-line properties in the "Clientclass" field, for example, 'OBEXAPP_SalesOrderActionButton {"title":
Fixed

2024-03-18 14:17 UTC, valeg-etendo requested changes

2024-03-18 14:18 UTC, valeg-etendo requested changes

2024-03-18 14:18 UTC, valeg-etendo commented on docs/developer-guide/etendo-classic/how-to-guides/How_to_add_a_canvas_field_to_a_Form_or_Grid.md
> +A canvas field allows the user to add any visual component to a form or a row in a
Delete line break

2024-03-18 14:19 UTC, valeg-etendo requested changes

2024-03-18 14:19 UTC, valeg-etendo commented on docs/developer-guide/etendo-classic/how-to-guides/How_to_add_a_canvas_field_to_a_Form_or_Grid.md
> +This section is supported by an example module which shows examples of the code
Delete line break

2024-03-18 14:19 UTC, valeg-etendo commented on docs/developer-guide/etendo-classic/how-to-guides/How_to_add_a_canvas_field_to_a_Form_or_Grid.md
> +The code of the example module can be downloaded from this
Delete line break

2024-03-18 14:19 UTC, valeg-etendo commented on docs/developer-guide/etendo-classic/how-to-guides/How_to_add_a_canvas_field_to_a_Form_or_Grid.md
> +The next step is to create a new field in the tab, and set its client class
Delete line break

2024-03-18 14:19 UTC, valeg-etendo commented on docs/developer-guide/etendo-classic/how-to-guides/How_to_add_a_canvas_field_to_a_Form_or_Grid.md
> +When implementing your canvas, you should take into account that the canvas is
Delete line break

2024-03-20 11:11 UTC, valenvivaldi approved these changes

2024-03-20 13:13 UTC, isaiasb-etendo requested changes

2024-03-20 14:23 UTC, RomanMagnoli commented on docs/developer-guide/etendo-classic/how-to-guides/How_to_add_a_canvas_field_to_a_Form_or_Grid.md
> +##  Introduction
Fix. Added above

2024-03-20 14:26 UTC, RomanMagnoli commented on docs/developer-guide/etendo-classic/how-to-guides/How_to_add_a_canvas_field_to_a_Form_or_Grid.md
> +```javascript
Fixed

2024-03-20 19:32 UTC, isaiasb-etendo approved these changes

2024-03-20 20:10 UTC, merged