Feature EPL-875: add ean128 & mobile scan
etendosoftware/docs pull request #14
Opened 2023-08-31 13:25 UTC by JoaquinCorti

2023-09-04 12:13 UTC, valeg-etendo requested changes

2023-09-04 12:13 UTC, valeg-etendo commented on docs/developer-guide/etendo-classic/bundles/platform-extensions-bundle.md
> +### Overview
All modules have their Technical Aspects description and in this case only Overview and description of methods or classes are added.

2023-09-04 12:13 UTC, valeg-etendo commented on docs/developer-guide/etendo-classic/bundles/platform-extensions-bundle.md
> +### Overview
All modules have their Technical Aspects description and in this case only Overview and description of methods or classes are added.

2023-09-04 12:13 UTC, valeg-etendo commented on docs/developer-guide/etendo-classic/bundles/platform-extensions-bundle.md
EAN 128 and Mobile Scan modules must also be added to the bundle Overview.

2023-09-04 12:15 UTC, valeg-etendo requested changes

2023-09-04 12:15 UTC, valeg-etendo commented on docs/developer-guide/etendo-classic/bundles/platform-extensions-bundle.md
> +### SelectorFieldPropertyDataSource.java
Is it necessary to describe the classes of the module?

2023-09-14 12:39 UTC, sjcuello approved these changes

2023-09-14 20:09 UTC, isaiasb-etendo approved these changes

2023-09-14 20:22 UTC, merged