Feature/epl 1292
etendosoftware/docs pull request #140
Opened 2024-03-18 13:32 UTC by mapenglishservices

2024-03-18 14:23 UTC, isaiasb-etendo requested changes

2024-03-18 14:23 UTC, isaiasb-etendo commented on docs/developer-guide/etendo-classic/how-to-guides/How_to_create_a_Report.md
> +![](../../../assets/developer-guide/etendo-classic/how-to-guides/How_to_create_a_Report-1.png)
@valenvivaldi  esta imagen debería ser en IntelliJ y no en Eclipse

2024-03-18 14:32 UTC, valeg-etendo requested changes

2024-03-18 14:32 UTC, valeg-etendo commented on docs/developer-guide/etendo-classic/how-to-guides/How_to_create_a_Report.md
> +In this section, the user can find information about the steps required to create a new report in Etendo Classic. The example explained is a simple report with a list of
Delete line break

2024-03-18 14:32 UTC, valeg-etendo commented on docs/developer-guide/etendo-classic/how-to-guides/How_to_create_a_Report.md
> +create and modify JasperReports templates (.jrxml files).
Delete line break

2024-03-18 14:32 UTC, valeg-etendo commented on docs/developer-guide/etendo-classic/how-to-guides/How_to_create_a_Report.md
> +properly. In short, you need to make sure:
Delete line break

2024-03-18 14:32 UTC, valeg-etendo commented on docs/developer-guide/etendo-classic/how-to-guides/How_to_create_a_Report.md
> +first need to create a new project (`File` > `New` > `Project`).
Delete line break

2024-03-18 14:32 UTC, valeg-etendo commented on docs/developer-guide/etendo-classic/how-to-guides/How_to_create_a_Report.md
> +going to keep our Report and also the required configuration in the Application
Delete line break

2024-03-18 14:32 UTC, valeg-etendo commented on docs/developer-guide/etendo-classic/how-to-guides/How_to_create_a_Report.md
> +Later on, we will copy this .jrxml file inside our Etendo module that is
Delete line break

2024-03-18 14:32 UTC, valeg-etendo commented on docs/developer-guide/etendo-classic/how-to-guides/How_to_create_a_Report.md
> +Dictionary.
Delete line break

2024-03-18 14:32 UTC, valeg-etendo commented on docs/developer-guide/etendo-classic/how-to-guides/How_to_create_a_Report.md
> +in the database.
Delete line break

2024-03-18 14:32 UTC, valeg-etendo commented on docs/developer-guide/etendo-classic/how-to-guides/How_to_create_a_Report.md
> +of several methods that reside inside the *Etendo Runtime Environment* ,
Delete line break

2024-03-18 14:32 UTC, valeg-etendo commented on docs/developer-guide/etendo-classic/how-to-guides/How_to_create_a_Report.md
> +which cannot be executed at design time. For this reason, we provide a .jar file that encapsulates the following adapted methods of
Delete line break

2024-03-18 14:32 UTC, valeg-etendo commented on docs/developer-guide/etendo-classic/how-to-guides/How_to_create_a_Report.md
> +the `org.openbravo.erpCommon.utility.Utility` Class:
Delete line break

2024-03-18 14:32 UTC, valeg-etendo commented on docs/developer-guide/etendo-classic/how-to-guides/How_to_create_a_Report.md
> +*JasperStudio*, it suffices just to import the .jar file into the classpath
Delete line break

2024-03-18 14:32 UTC, valeg-etendo commented on docs/developer-guide/etendo-classic/how-to-guides/How_to_create_a_Report.md
> +of the project within JasperStudio.
Delete line break

2024-03-18 14:32 UTC, valeg-etendo commented on docs/developer-guide/etendo-classic/how-to-guides/How_to_create_a_Report.md
> +report, or one of the Company logos in the application.
Delete line break

2024-03-18 14:32 UTC, valeg-etendo commented on docs/developer-guide/etendo-classic/how-to-guides/How_to_create_a_Report.md
> +Images loaded with this method must not have alpha channel. A transparency
Delete line break

2024-03-18 14:32 UTC, valeg-etendo commented on docs/developer-guide/etendo-classic/how-to-guides/How_to_create_a_Report.md
> +IMAGEID needs to be the UUID of the image you want to show. You could set this
Delete line break

2024-03-18 14:32 UTC, valeg-etendo commented on docs/developer-guide/etendo-classic/how-to-guides/How_to_create_a_Report.md
> +show. You could set this value using a Jasper argument. An example could be
Delete line break

2024-03-18 14:32 UTC, valeg-etendo commented on docs/developer-guide/etendo-classic/how-to-guides/How_to_create_a_Report.md
> +`org.openbravo.erpCommon.utility.Utility.showImageLogo("yourcompanydoc","4387D62C6486481AB3D148442A6AD34E")̣` being `4387D62C6486481AB3D148442A6AD34E`
Delete line break

2024-03-18 14:32 UTC, valeg-etendo commented on docs/developer-guide/etendo-classic/how-to-guides/How_to_create_a_Report.md
> +the organization ID.
Delete line break

2024-03-18 14:32 UTC, valeg-etendo commented on docs/developer-guide/etendo-classic/how-to-guides/How_to_create_a_Report.md
> +our module. When using Process Definition to generate a Report, templates need
Delete line break

2024-03-18 14:32 UTC, valeg-etendo commented on docs/developer-guide/etendo-classic/how-to-guides/How_to_create_a_Report.md
> +We must copy the .jrxml template file generated with Jaspersoft Studio into
Delete line break

2024-03-18 14:32 UTC, valeg-etendo commented on docs/developer-guide/etendo-classic/how-to-guides/How_to_create_a_Report.md
> +to be stored in the web folder of the module. In our example, we place it in
Delete line break

2024-03-18 14:32 UTC, valeg-etendo commented on docs/developer-guide/etendo-classic/how-to-guides/How_to_create_a_Report.md
> +Dictionary, you need to compile to generate the necessary code.
Delete line break

2024-03-18 14:32 UTC, valeg-etendo commented on docs/developer-guide/etendo-classic/how-to-guides/How_to_create_a_Report.md
> +If we want to have a particular format in a cell of our XLS report, and for
Delete line break

2024-03-18 14:32 UTC, valeg-etendo commented on docs/developer-guide/etendo-classic/how-to-guides/How_to_create_a_Report.md
> +To override this configuration, the following must be done inside the .jrxml
Delete line break

2024-03-18 14:32 UTC, valeg-etendo commented on docs/developer-guide/etendo-classic/how-to-guides/How_to_create_a_Report.md
> +    The decimal and thousands *separators* used for the numeric
Delete line break

2024-03-18 14:32 UTC, valeg-etendo commented on docs/developer-guide/etendo-classic/how-to-guides/How_to_create_a_Report.md
> +    cells exported in this way, will be those defined inside the spreadsheet
Delete line break

2024-03-18 14:32 UTC, valeg-etendo commented on docs/developer-guide/etendo-classic/how-to-guides/How_to_create_a_Report.md
> +When printing a report in the application, it is previously compiled at
Delete line break

2024-03-18 14:32 UTC, valeg-etendo commented on docs/developer-guide/etendo-classic/how-to-guides/How_to_create_a_Report.md
> +runtime. The result of this report compilation is cached if there are no
Delete line break

2024-03-18 14:32 UTC, valeg-etendo commented on docs/developer-guide/etendo-classic/how-to-guides/How_to_create_a_Report.md
> +Besides, it is possible to handle the state of this cache through a JMX
Delete line break

2024-03-18 14:32 UTC, valeg-etendo commented on docs/developer-guide/etendo-classic/how-to-guides/How_to_create_a_Report.md
> +It is possible to generate barcodes from JasperReports, using barcode4j or
Delete line break

2024-03-18 14:32 UTC, valeg-etendo commented on docs/developer-guide/etendo-classic/how-to-guides/How_to_create_a_Report.md
> +In Platform Features module, there is an example of a report making use of
Delete line break

2024-03-18 14:45 UTC, isaiasb-etendo requested changes

2024-03-18 14:45 UTC, isaiasb-etendo commented on docs/developer-guide/etendo-classic/how-to-guides/How_to_create_a_Report.md
> +    ```bash
Falta el terminal 

``bash title="Terminal"
./gradlew smartbuild
``

2024-03-19 18:48 UTC, isaiasb-etendo approved these changes

2024-03-19 20:08 UTC, valeg-etendo commented on mkdocs.yml
> +        - How to create a Report: developer-guide/etendo-classic/concepts/How_to_create_a_Report.md
```suggestion
        - How to Create a Report: developer-guide/etendo-classic/concepts/How_to_create_a_Report.md
```

2024-03-19 20:08 UTC, valeg-etendo commented on mkdocs.yml
> +        - How to create a Report: developer-guide/etendo-classic/how-to-guides/How_to_create_a_Report.md
```suggestion
        - How to Create a Report: developer-guide/etendo-classic/how-to-guides/How_to_create_a_Report.md
```

2024-03-19 20:08 UTC, valeg-etendo commented on docs/developer-guide/etendo-classic/how-to-guides/How_to_create_a_Report.md
> +#  How to create a Report
```suggestion
#  How to Create a Report
```

2024-03-19 20:12 UTC, valeg-etendo commented on mkdocs.yml
> +        - How to create a Report: developer-guide/etendo-classic/concepts/How_to_create_a_Report.md
@mapenglishservices @isaiasb-etendo Check duplicate page

2024-03-20 11:52 UTC, valenvivaldi approved these changes

2024-03-25 15:03 UTC, valeg-etendo approved these changes

2024-03-25 15:06 UTC, merged