Feature EPL-1428: How to create a table
etendosoftware/docs pull request #155
Opened 2024-04-03 19:10 UTC by mapenglishservices

…ce information.

2024-04-03 19:54 UTC, valeg-etendo requested changes

2024-04-03 19:54 UTC, valeg-etendo commented on docs/developer-guide/etendo-classic/how-to-guides/How_to_create_a_Table.md
> +being. The record belonging to a particular employee with the latest Valid From Date is the salary that is valid today. Note that employees are already inside the system contained in the C_BPARTNER d
@mapenglishservices Remove line break

2024-04-03 19:54 UTC, valeg-etendo commented on docs/developer-guide/etendo-classic/how-to-guides/How_to_create_a_Table.md
> +table that will hold the actual salaries.
@mapenglishservices Remove line break

2024-04-03 19:54 UTC, valeg-etendo commented on docs/developer-guide/etendo-classic/how-to-guides/How_to_create_a_Table.md
> +construct dropdown lists of records of that particular table. By default all columns with column name _Name_ are set as an identifier. In case there is no column with this _Name_ , no identifier is s
@mapenglishservices Remove line break

2024-04-03 19:54 UTC, valeg-etendo commented on docs/developer-guide/etendo-classic/how-to-guides/How_to_create_a_Table.md
> +detected correctly, however, some need revising:
@mapenglishservices Remove line break

2024-04-03 19:54 UTC, valeg-etendo commented on docs/developer-guide/etendo-classic/how-to-guides/How_to_create_a_Table.md
> +![](/assets/developer-guide/etendo-classic/how-to-guides/How_to_create_a_Table-1.png){:.legacy-image-style}
```suggestion
![](../../../assets/developer-guide/etendo-classic/how-to-guides/How_to_create_a_Table-1.png){:.legacy-image-style}
```

2024-04-04 18:21 UTC, valenvivaldi commented on docs/developer-guide/etendo-classic/how-to-guides/How_to_create_a_Table.md
> +HT_SALARY_ID  |  CHAR  |  32  |  The primary key of the table that must follow
type VARCHAR 32


varchar32  != char32

2024-04-04 18:22 UTC, valenvivaldi commented on docs/developer-guide/etendo-classic/how-to-guides/How_to_create_a_Table.md
> +    CREATE TABLE ht_salary
here is fine

2024-04-04 18:23 UTC, valenvivaldi commented on docs/developer-guide/etendo-classic/how-to-guides/How_to_create_a_Table.md
> +![](/assets/developer-guide/etendo-classic/how-to-guides/How_to_create_a_Table-5.png){: .legacy-image-style}
this images are new or old? because if there are new, then must remove the legacy style

2024-04-08 14:12 UTC, valeg-etendo requested changes

2024-04-08 14:12 UTC, valeg-etendo commented on docs/developer-guide/etendo-classic/how-to-guides/How_to_create_a_Table.md
> +![](/assets/developer-guide/etendo-classic/how-to-guides/How_to_create_a_Table-3.png){: .legacy-image-style}
```suggestion
![](../../../assets/developer-guide/etendo-classic/how-to-guides/How_to_create_a_Table-3.png)
```

2024-04-08 14:12 UTC, valeg-etendo commented on docs/developer-guide/etendo-classic/how-to-guides/How_to_create_a_Table.md
> +![](/assets/developer-guide/etendo-classic/how-to-guides/How_to_create_a_Table-4.png){: .legacy-image-style}
```suggestion
![](../../../assets/developer-guide/etendo-classic/how-to-guides/How_to_create_a_Table-4.png)
```

2024-04-08 14:12 UTC, valeg-etendo commented on docs/developer-guide/etendo-classic/how-to-guides/How_to_create_a_Table.md
> +![](/assets/developer-guide/etendo-classic/how-to-guides/How_to_create_a_Table-5.png){: .legacy-image-style}
```suggestion
![](../../../assets/developer-guide/etendo-classic/how-to-guides/How_to_create_a_Table-5.png)
```

2024-04-08 15:32 UTC, closed without merging