feature EPL-1407: How to add Columns to a Table
etendosoftware/docs pull request #168
Opened 2024-04-23 14:26 UTC by Tomas-Vesco

2024-04-23 16:44 UTC, RomanMagnoli approved these changes

2024-04-24 11:43 UTC, valeg-etendo requested changes

2024-04-24 11:43 UTC, valeg-etendo commented on mkdocs.yml
> +        - How to add Columns to a Table: developer-guide/etendo-classic/how-to-guides/How_to_add_Columns_to_a_Table.md
```suggestion
        - How to Add Columns to a Table: developer-guide/etendo-classic/how-to-guides/how-to-add-columns-to-a-table.md
```

2024-04-24 11:43 UTC, valeg-etendo commented on docs/developer-guide/etendo-classic/how-to-guides/How_to_add_Columns_to_a_Table.md
> +In this section, the user can find information about how to extend the table created in the [How to Create a Table](../../../developer-guide/etendo-classic/how-to-guides/How_to_create_a_Table.md) sec
@isaiasb-etendo Is this change suggestion correct?

```suggestion
In this section, the user can find information about how to extend the table created in the [How to Create a Table](how-to-create-a-table.md) section to include additional fields.
```

2024-04-24 11:43 UTC, valeg-etendo commented on docs/developer-guide/etendo-classic/how-to-guides/How_to_add_Columns_to_a_Table.md
> +---
Rename as `how-to-add-columns-to-a-table.md`

2024-04-24 12:06 UTC, valeg-etendo requested changes

2024-04-24 12:06 UTC, valeg-etendo commented on docs/developer-guide/etendo-classic/how-to-guides/How_to_add_Columns_to_a_Table.md
> +```sql
```suggestion
```sql title="SQL script"
```

2024-04-24 12:06 UTC, valeg-etendo commented on docs/developer-guide/etendo-classic/how-to-guides/How_to_add_Columns_to_a_Table.md
> +*PostgreSQL*
```suggestion
```

2024-04-24 12:06 UTC, valeg-etendo commented on docs/developer-guide/etendo-classic/how-to-guides/How_to_add_Columns_to_a_Table.md
> +Column name  |  Type  |  Length  |  Note
@Tomas-Vesco Fix table formatting

2024-04-26 12:09 UTC, valenvivaldi approved these changes

2024-04-26 15:31 UTC, valeg-etendo approved these changes

2024-04-26 15:31 UTC, merged