Feature EPL-890: add documentation in etendo classic subapp bundle
etendosoftware/docs pull request #18
Opened 2023-09-08 20:15 UTC by JoaquinCorti

2023-09-08 20:27 UTC, isaiasb-etendo approved these changes

2023-09-11 07:29 UTC, valeg-etendo requested changes

2023-09-11 07:29 UTC, valeg-etendo commented on docs/products/etendo-mobile/bundles/etendo-classic-subapp-extensions/etendo-classic-subapp-extensions.md
> +In the welcome window, the user can enter Profile, Settings and Navigation Menu.
```suggestion
In the Welcome window, the user can enter Profile, Settings and Navigation Menu.
```

2023-09-11 07:29 UTC, valeg-etendo commented on docs/products/etendo-mobile/bundles/etendo-classic-subapp-extensions/etendo-classic-subapp-extensions.md
> +- Access the window Profile (clicking the profile picture)
```suggestion
- Access the Profile window (clicking the profile picture)
```

2023-09-11 07:29 UTC, valeg-etendo commented on docs/products/etendo-mobile/bundles/etendo-classic-subapp-extensions/etendo-classic-subapp-extensions.md
> +Considering as an example the Sales invoice window, the preview of each record provides information regarding the document number and invoice date.
```suggestion
Considering as an example the Sales Invoice window, the preview of each record provides information regarding the document number and invoice date.
```

2023-09-11 07:29 UTC, valeg-etendo commented on docs/products/etendo-mobile/bundles/etendo-classic-subapp-extensions/etendo-classic-subapp-extensions.md
> +Continuing with the example of the Sales invoice window, the available filters are the document number, which will be entered in the search bar together with the invoice date.
```suggestion
Continuing with the example of the Sales Invoice window, the available filters are the document number, which will be entered in the search bar together with the invoice date.
```

2023-09-11 08:08 UTC, valeg-etendo requested changes

2023-09-11 12:25 UTC, valeg-etendo approved these changes

2023-09-11 14:19 UTC, merged