Feature EPL-1470: Add Taxes, 303 and 390 fixes to migration doc
etendosoftware/docs pull request #182
Opened 2024-05-13 13:40 UTC by RubenEtendo

2024-05-13 14:56 UTC, valeg-etendo approved these changes

2024-05-13 14:56 UTC, valeg-etendo commented on docs/developer-guide/etendo-classic/bundles/spain-localization/known-issues.md
> +    !!! warning
@RubenEtendo Block should not be added inside other block

2024-05-13 14:56 UTC, valeg-etendo commented on docs/developer-guide/etendo-classic/bundles/spain-localization/known-issues.md
> +    !!! warning
@RubenEtendo Block should not be added inside other block

2024-05-13 18:27 UTC, valeg-etendo requested changes

2024-05-13 18:27 UTC, valeg-etendo commented on docs/developer-guide/etendo-classic/getting-started/migration-from-openbravo/migrating-to-etendo-from-openbravo.md
> +To solve issues with taxes arising from these modules being migrated from Openbravo to Etendo, refer to the related [Spain Localization Known Issue](../../../../whats-new/release-notes/etendo-classic
```suggestion
To solve issues with taxes arising from these modules being migrated from Openbravo to Etendo, refer to the related [Known Issue](../../../../whats-new/release-notes/etendo-classic/known-issues.md/#ee-856-dataset-de-declaraciones-de-impuestos-modelo-390-duplica-datos-para-el-2022-cuando-se-aplica-a-un-servidor-migrado-de-openbravo-a-etendo-despues-del-01-2023) 
```

2024-05-13 18:27 UTC, valeg-etendo commented on docs/developer-guide/etendo-classic/getting-started/migration-from-openbravo/migrating-to-etendo-from-openbravo.md
> +To solve issues with taxes arising from these modules being migrated from Openbravo to Etendo, refer to the related [Spain Localization Known Issue](../../../../whats-new/release-notes/etendo-classic
```suggestion
To solve issues with taxes arising from these modules being migrated from Openbravo to Etendo, refer to the related [Known Issue](../../../../whats-new/release-notes/etendo-classic/known-issues.md/#ee-808-problema-al-intentar-importar-el-dataset-taxes-configuration-for-spain-si-el-entorno-ya-tiene-aplicado-el-dataset-de-impuestos-temporales-303-de-openbravo) 
```

2024-05-14 18:05 UTC, valeg-etendo approved these changes

2024-05-16 12:54 UTC, isaiasb-etendo approved these changes

2024-05-16 13:32 UTC, Matias-Bernal requested changes

2024-05-16 15:35 UTC, RubenEtendo commented on docs/whats-new/release-notes/etendo-classic/known-issues.md
> +??? success "EE-856 Solved"
Done!

2024-05-16 19:40 UTC, valeg-etendo requested changes

2024-05-16 19:40 UTC, valeg-etendo commented on docs/whats-new/release-notes/etendo-classic/known-issues.md
> +    #### Workaround
```suggestion
```

2024-05-17 00:13 UTC, Matias-Bernal approved these changes

2024-05-17 10:45 UTC, RubenEtendo commented on docs/whats-new/release-notes/etendo-classic/known-issues.md
> +    #### Workaround
Done!

2024-05-17 11:40 UTC, valeg-etendo approved these changes

2024-05-17 11:45 UTC, merged