EPL-1454: How to create a pick and execute process
etendosoftware/docs pull request #189
Opened 2024-05-21 16:50 UTC by Tomas-Vesco

2024-05-21 18:27 UTC, valeg-etendo requested changes

2024-05-21 18:27 UTC, valeg-etendo commented on docs/developer-guide/etendo-classic/how-to-guides/how-to-create-a-pick-and-execute-process.md
> +      For more information, read [How to add a field to a Window Tab](../how-to-guides/how-to-add-a-field-to-a-window-tab).
```suggestion
      For more information, visit [How to add a field to a Window Tab](how-to-add-a-field-to-a-window-tab).
```

2024-05-21 18:27 UTC, valeg-etendo commented on docs/developer-guide/etendo-classic/how-to-guides/how-to-create-a-pick-and-execute-process.md
> +
```suggestion
```

2024-05-21 18:27 UTC, valeg-etendo commented on docs/developer-guide/etendo-classic/how-to-guides/how-to-create-a-pick-and-execute-process.md
> +  * [Action Handler](how-to-create-client-event-handler-actions.md)
```suggestion

```

2024-05-21 18:29 UTC, valeg-etendo commented on docs/developer-guide/etendo-classic/how-to-guides/how-to-create-a-pick-and-execute-process.md
>  development:
```suggestion
development:

```

2024-05-22 15:41 UTC, valeg-etendo approved these changes

2024-05-22 15:51 UTC, Gremiger approved these changes

2024-05-22 18:03 UTC, RomanMagnoli approved these changes

2024-05-22 18:04 UTC, merged