Feature/EPL-1462: Development Build Tasks
etendosoftware/docs pull request #201
Opened 2024-05-31 18:02 UTC by Tomas-Vesco

2024-06-01 20:18 UTC, valenvivaldi requested changes

2024-06-01 20:18 UTC, valenvivaldi commented on docs/developer-guide/etendo-classic/concepts/development-build-tasks.md
> +The only difference with the local development is in the `local` parameter which makes the process to update the database in case the `xml` files were changed.
Y sobre los cambios locales no dice nada? me parece que seria bueno hacer referencia sobre la posibilidad de los cambios locales y el dforce

2024-06-05 14:23 UTC, Tomas-Vesco commented on docs/developer-guide/etendo-classic/concepts/development-build-tasks.md
> +The only difference with the local development is in the `local` parameter which makes the process to update the database in case the `xml` files were changed.
Eso esta incluido en las tablas de mas abajo.

2024-06-05 18:27 UTC, valenvivaldi approved these changes

2024-06-05 19:12 UTC, RomanMagnoli approved these changes

2024-06-07 14:40 UTC, merged