Feature EPL 1501: Selectors
etendosoftware/docs pull request #205
Opened 2024-06-10 14:01 UTC by Tomas-Vesco

2024-06-10 18:56 UTC, RomanMagnoli approved these changes

2024-06-10 19:06 UTC, valeg-etendo requested changes

2024-06-10 19:06 UTC, valeg-etendo commented on docs/developer-guide/etendo-classic/concepts/selectors.md
> +  * Parent Reference **must** be set to OBUISEL_Selector_Reference
```suggestion
  * Parent Reference **must** be set to `OBUISEL_Selector_Reference` 
```

2024-06-10 19:06 UTC, valeg-etendo commented on docs/developer-guide/etendo-classic/concepts/selectors.md
> +    When using properties of the entity in the whereclause always the prefix 'e.' has to be used, for example 'e.seqno'
```suggestion
    When using properties of the entity in the whereclause always the prefix `e.` has to be used, for example `e.seqno`  
```

2024-06-10 19:06 UTC, valeg-etendo commented on docs/developer-guide/etendo-classic/concepts/selectors.md
> +Then, in the reference field, choose OBUISEL_Selector Reference. Then in the next combo box **Reference Search Key**, select the specific selector. In the screenshot below a Business Partner Selector
```suggestion
Then, in the reference field, choose `OBUISEL_Selector` Reference. Then in the next combo box **Reference Search Key**, select the specific selector. In the screenshot below a Business Partner Selector is chosen.
```

2024-06-10 19:06 UTC, valeg-etendo commented on docs/developer-guide/etendo-classic/concepts/selectors.md
> +  * add/remove columns from the popup grid
```suggestion
  * Add/remove columns from the popup grid.
```

2024-06-10 19:06 UTC, valeg-etendo commented on docs/developer-guide/etendo-classic/concepts/selectors.md
> +  * change the where clause
```suggestion
  * Change the where clause.
```

2024-06-10 19:06 UTC, valeg-etendo commented on docs/developer-guide/etendo-classic/concepts/selectors.md
> +  * change the fields which are searched as part of the suggestion box display
```suggestion
  * Change the fields which are searched as part of the suggestion box display.
```

2024-06-10 19:06 UTC, valeg-etendo commented on docs/developer-guide/etendo-classic/concepts/selectors.md
> +You can use the New Selectors in manual code (not generated by WAD). You must include all the necessary JS imports. There is an empty hook function **onValueChanged** that you can override in your ma
```suggestion
You can use the New Selectors in manual code (not generated by WAD). You must include all the necessary JS imports. There is an empty hook function `onValueChanged` that you can override in your manual window, to perform any custom action. When the user picks a row, this function gets executed. By default it does not do anything.
```

2024-06-10 19:06 UTC, valeg-etendo commented on docs/developer-guide/etendo-classic/concepts/selectors.md
> +  * they can be completely defined without manual coding.
```suggestion
  * They can be completely defined without manual coding. 
```

2024-06-10 19:06 UTC, valeg-etendo commented on docs/developer-guide/etendo-classic/concepts/selectors.md
> +  * the selector definition (columns, search criteria, where clause) can be changed at runtime without re-compiling or re-starting the system.
```suggestion
  * The selector definition (columns, search criteria, where clause) can be changed at runtime without re-compiling or re-starting the system. 
```

2024-06-10 19:06 UTC, valeg-etendo commented on docs/developer-guide/etendo-classic/concepts/selectors.md
> +  * the selector makes it very easy to show linked information of a selected entity or search, sort and filter on linked information.
```suggestion
  * The selector makes it very easy to show linked information of a selected entity or search, sort and filter on linked information. 
```

2024-06-10 19:06 UTC, valeg-etendo commented on docs/developer-guide/etendo-classic/concepts/selectors.md
> +  * the selector suggestion box, as well as the popup grid, support paging with lookahead. This makes them also suitable for large datasets.
```suggestion
  * The selector suggestion box, as well as the popup grid, support paging with lookahead. This makes them also suitable for large datasets. 
```

2024-06-10 19:06 UTC, valeg-etendo commented on docs/developer-guide/etendo-classic/concepts/selectors.md
> +  * the reference definition
```suggestion
  * The reference definition.
```

2024-06-10 19:06 UTC, valeg-etendo commented on docs/developer-guide/etendo-classic/concepts/selectors.md
> +  * the selector header defining which table to select from and the where clause to use
```suggestion
  * The selector header defining which table to select from and the where clause to use.
```

2024-06-10 19:06 UTC, valeg-etendo commented on docs/developer-guide/etendo-classic/concepts/selectors.md
> +  * the selector fields which define which columns are searched and what columns are shown in the popup window.
```suggestion
  * The selector fields which define which columns are searched and what columns are shown in the popup window.
```

2024-06-11 13:08 UTC, Leo-Echenique commented
Estimado, el error del git police se debe a que el primer commit contiene más de los caracteres permitidos.-

2024-06-11 18:07 UTC, Gremiger approved these changes

2024-06-12 12:55 UTC, valeg-etendo requested changes

2024-06-12 13:44 UTC, valeg-etendo approved these changes

2024-06-12 13:47 UTC, merged