Feature EE-972: Create Wiki Documentation for G/J Journal Clone
etendosoftware/docs pull request #209
Opened 2024-06-12 19:41 UTC by mapenglishservices

2024-06-12 23:34 UTC, valeg-etendo requested changes

2024-06-12 23:34 UTC, valeg-etendo commented on docs/user-guide/etendo-classic/optional-features/bundles/financial-extensions/overview.md
> +:octicons-package-16: Javapackage: com.etendoerp.gljournal.clone
@mapenglishservices 
```suggestion
:octicons-package-16: Javapackage: `com.etendoerp.gljournal.clone`
```

2024-06-12 23:34 UTC, valeg-etendo commented on docs/user-guide/etendo-classic/optional-features/bundles/financial-extensions/overview.md
@mapenglishservices Maybe we could sort the modules alphabetically, no?

2024-06-13 11:32 UTC, ivanrobledofutit approved these changes

2024-06-28 17:24 UTC, valeg-etendo approved these changes

2024-06-28 17:41 UTC, merged