Feature EPL-1515: How To Exclude Database Physical Objects From Model
etendosoftware/docs pull request #212
Opened 2024-06-13 19:12 UTC by Leo-Echenique

2024-06-13 19:51 UTC, Tomas-Vesco commented on docs/developer-guide/etendo-classic/how-to-guides/how-to-exclude-database-physical-objects-from-model.md
> +      </vector>
```xml
    <?xml version="1.0"?>
      <vector>
        <excludedTable name="TEST_TABLE"/>
        <excludedView name="TEST_VIEW"/>
        <excludedFunction name="TEST_FUNCTION"/>
        <excludedTrigger name="TEST_TRIGGER"/>
        <excludedSequence name="TEST\_%"/>
      </vector>
```

2024-06-13 19:51 UTC, Tomas-Vesco requested changes

2024-06-13 19:51 UTC, Tomas-Vesco commented on docs/developer-guide/etendo-classic/how-to-guides/how-to-exclude-database-physical-objects-from-model.md
> +      </vector>
```xml
    <?xml version="1.0"?>
      <vector>
        <excludedTable name="TEST_TABLE"/>
        <excludedView name="TEST_VIEW"/>
        <excludedFunction name="TEST_FUNCTION"/>
        <excludedTrigger name="TEST_TRIGGER"/>
        <excludedSequence name="TEST\_%"/>
      </vector>
```

2024-06-13 19:54 UTC, Tomas-Vesco commented on docs/developer-guide/etendo-classic/how-to-guides/how-to-exclude-database-physical-objects-from-model.md
> +The use of [SQL Wildcards](https://www.w3schools.com/sql/sql_wildcards.asp){target="\_blank"} is supported, so the same treatment will be done to all sequences whose name begins with **TEST_** . All
```suggestion
The use of [SQL Wildcards](https://www.w3schools.com/sql/sql_wildcards.asp){target="\_blank"} is supported, so the same treatment will be done to all sequences whose name begins with **TEST_**. All exclusions whose name contain the `%` character will be treated as wildcards. When defining an exclusion using a wildcard, remember to escape with a backslash the `_` characters, unless it is meant to be used as a substitute for any single character.
```

2024-06-13 19:59 UTC, Tomas-Vesco commented on docs/developer-guide/etendo-classic/how-to-guides/how-to-exclude-database-physical-objects-from-model.md
> +      </vector>
```suggestion
    ```xml
    <?xml version="1.0"?>
      <vector>
        <excludedTable name="TEST_TABLE"/>
        <excludedView name="TEST_VIEW"/>
        <excludedFunction name="TEST_FUNCTION"/>
        <excludedTrigger name="TEST_TRIGGER"/>
        <excludedSequence name="TEST\_%"/>
      </vector>
    ```
```

2024-06-14 13:31 UTC, Gremiger approved these changes

2024-06-14 13:50 UTC, RomanMagnoli approved these changes

2024-06-14 17:13 UTC, merged