Feature ESL-209: Add Batuz documentation
etendosoftware/docs pull request #280
Opened 2024-10-16 17:39 UTC by AyelenGarcia01

2024-10-16 18:09 UTC, RubenEtendo commented on docs/user-guide/etendo-classic/optional-features/bundles/spain-localization/batuz.md
> +3.  Aplique este dataset a la organización *****
Esto como se ve en la documentación? En la preview me aparecen directamente todos los asteriscos

2024-10-16 18:11 UTC, RubenEtendo commented on docs/user-guide/etendo-classic/optional-features/bundles/spain-localization/batuz.md
> +- **Descripcion de Facturas**: Indique el texto que se incluirá en el campo **DescripcionFactura** del XML enviado a Batuz.
Agregale el acento a descripción

2024-10-16 18:11 UTC, RubenEtendo commented on docs/user-guide/etendo-classic/optional-features/bundles/spain-localization/batuz.md
> +- **Utilizar descripcion también para nombre de producto**: Si está activado, se usará el valor de DescripcionFactura en el campo **DescripcionDetalle** del XML de la factura.
Idem a lo dicho arriba

2024-10-16 18:19 UTC, AyelenGarcia01 commented on docs/user-guide/etendo-classic/optional-features/bundles/spain-localization/batuz.md
> +3.  Aplique este dataset a la organización *****
En la documentación solo aparece *****

2024-10-16 18:28 UTC, AxelAlcaraz commented on docs/user-guide/etendo-classic/optional-features/bundles/spain-localization/batuz.md
> +Tal y como sucede con otros procesos de Etendo, éstos podrán configurarse para ser ejecutados de forma inmediata, planificada o programada con una cierta frecuencia, donde permitirán el alta masiva d
éstos -> estos

2024-10-16 18:29 UTC, AxelAlcaraz requested changes
Correccion tilde

2024-10-16 18:39 UTC, AxelAlcaraz approved these changes

2024-10-16 18:48 UTC, RubenEtendo approved these changes

2024-10-21 17:10 UTC, AyelenGarcia01 commented
@isaiasb-etendo te menciono para cuando tengas un tiempito, si es posible, puedas revisarlo. Gracias.

2024-10-22 02:00 UTC, isaiasb-etendo commented on docs/user-guide/etendo-classic/optional-features/bundles/spain-localization/batuz.md
> +*No olvide añadir el certificado necesario en los adjuntos.*
Esto podría  ser un bloque  info

2024-10-22 02:06 UTC, isaiasb-etendo commented
@AyelenGarcia01  está muy bien, lo único que faltaría en la sección overview agregar un link a este nuevo modulo 
y de paso cambia el orden, está bien que estén ordenadas las páginas alfabéticamente en el menú, pero el overview debería ser la primer pagina 
<img width="1368" alt="image" src="https://github.com/user-attachments/assets/067c88ea-7fcb-48fc-a9ef-ad07cfcfe874">

2024-10-22 02:07 UTC, isaiasb-etendo approved these changes

2024-10-22 18:51 UTC, closed without merging