Feature ETP-675: Add Code Run Assistant documentation
etendosoftware/docs pull request #296
Opened 2024-11-07 17:57 UTC by fran-roig

2024-11-08 13:45 UTC, isaiasb-etendo commented on docs/developer-guide/etendo-copilot/bundles/dev-assistant.md
> +
@fran-roig is missing to document the tool he uses

2024-11-08 14:19 UTC, isaiasb-etendo commented on docs/developer-guide/etendo-copilot/bundles/dev-assistant.md
Agregar botón en el overview,  que te lleve al nuevo asistente

2024-11-08 14:53 UTC, valeg-etendo requested changes

2024-11-08 14:53 UTC, valeg-etendo commented on docs/developer-guide/etendo-copilot/bundles/dev-assistant.md
> +#### **Functionality**
```suggestion
#### Functionality
```

2024-11-08 14:53 UTC, valeg-etendo commented on docs/developer-guide/etendo-copilot/bundles/dev-assistant.md
> +#### **Usage Example**
```suggestion
#### Usage Example
```

2024-11-08 22:20 UTC, isaiasb-etendo approved these changes

2024-11-11 11:36 UTC, valeg-etendo approved these changes

2024-11-11 11:37 UTC, merged