Feature EPL-1076: Problem in css recompilation documentation
etendosoftware/docs pull request #39
Opened 2023-10-30 13:32 UTC by tomyrodeghiero

I've addressed the issue related to the CSS compilation in our documentation. Key changes include:

- Updated the installation instructions for **Node.js** using **NVM** in **Linux**.
- Added an alternative method for users facing issues with the `curl` command during installation.

2023-10-30 22:43 UTC, Gremiger approved these changes

2023-10-31 14:24 UTC, RomanMagnoli approved these changes

2023-11-01 11:38 UTC, sebastianbarrozo requested changes

2023-11-01 11:38 UTC, sebastianbarrozo commented on docs/developer-guide/etendo-classic/developer-tools/etendo-gradle-plugin.md
> +            sudo snap remove curl
This tools: snap and apt are platform dependent. This help is for ubuntu only?

2023-11-02 12:40 UTC, sebastianbarrozo approved these changes

2023-11-02 12:47 UTC, merged