Feature EPL-1213: Write a basic guide of RX concepts
etendosoftware/docs pull request #80
Opened 2024-01-19 19:16 UTC by sebastianbarrozo

2024-01-19 19:52 UTC, RomanMagnoli approved these changes

2024-01-31 16:05 UTC, RomanMagnoli approved these changes

2024-02-23 19:23 UTC, Gremiger approved these changes

2024-02-26 11:31 UTC, isaiasb-etendo requested changes

2024-02-26 11:31 UTC, isaiasb-etendo commented on docs/developer-guide/etendo-rx/getting-started/requirements.md
> +The requirements are those registered on [Requirements](/software/getting-started/requirements/).
This link does not exist. Remove it

2024-04-23 19:30 UTC, RomanMagnoli commented
Checkear PR! Es necesario revisarlo o se declina?

2024-05-02 13:24 UTC, Gremiger commented
@isaiasb-etendo The push that you did solved your comment? If yes, please approve the PR so Seba can merge it. Otherwise, let us (and @sebastianbarrozo) know so we can fix it. 

This PR is without activity since last week.

2024-05-03 12:43 UTC, isaiasb-etendo commented
> @isaiasb-etendo The push that you did solved your comment? If yes, please approve the PR so Seba can merge it. Otherwise, let us (and @sebastianbarrozo) know so we can fix it.
> 
> This PR is without activity since last week.

@Gremiger @sebastianbarrozo  there is still one reference to a page that does not exist

2024-05-03 12:46 UTC, closed without merging